### ISSUE TITLE
Running or Debugging a test in a workspace crate does not work

### ISSUE THREAD

**Issue by agentsim** [hdevalke/rust-test-lens#1]
I have a project organized as a workspace (has `[workspace]` in the root `Cargo.toml`).

To run unit tests in one of the dependent crates, I execute `cargo test -p my_crate`. Clicking the 'Run Test' or 'Debug Test' links from this extension does not work in `my_crate`, it results trying to run the test against the root crate instead.

**Comment by hdevalke** [comment]
The run test is not provided by this extension, but by the [rls-vscode](https://github.com/rust-lang-nursery/rls-vscode) extension. Please create an issue there for the 'Run Test' problem.

For the debug problem, could you provide the output of the LLDB extension? It should contain something like: 

```
Running `cargo test --no-run --package=<package-name> --message-format=json`...
```

The package option should be set.

If not, is it possible to provide a minimal example project and the version of vscode and vscode-lldb?

**Comment by agentsim** [comment]
The output in the debug console when I try to debug the test is:

> Display settings: variable format=auto, show disassembly=auto, numeric pointer values=off, container summaries=on.
> Launching /home/me/src/my-projcet-rs/target/debug/my_project-609a98035054255e parse_generated_prop
> 
> running 0 tests
> 
> test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 24 filtered out
> 
> Process exited with code 0.
> 

The command it is executing refers to 'my_project' instead of 'my_crate'

**Comment by hdevalke** [comment]
That is the output of the debug console. I would like to see the output of the output of the LLDB extension (output tab right from debug console tab).

It might be an issue in how a filename is matched with the package path (see [`getPackage`](https://github.com/hdevalke/rust-test-lens/blob/2207b8859a472ada232c197b2968c6d98a284c5b/src/RustTests.ts#L14)). As `.../my_project` is also a prefix for `.../myproject/my_crate`. I could update the code to match the longest matching prefix.

To  you paste the outcome of this command:

```sh
cargo metadata --no-deps --format-version=1 | jq '.packages[] | .name,.manifest_path'
```

**Comment by hdevalke** [comment]
I could reproduce the problem and made a fix. It should be available in the vscode marketplace soon.
Let me know if it solved your exact problem.

**Comment by agentsim** [comment]
Yes, that solved my problem. Thanks!
