### ISSUE TITLE
The args are wrong when the test returns an Result in the same line

### ISSUE THREAD

**Issue by imzeadom** [hdevalke/rust-test-lens#10]
e.g. For test
```
#[test]
fn simple_test() -> Result<(), Error> {
  // some code here...
  Ok(())
}
```
The args is somehow ""simple_test() -> Result<"". It should be "simple_test".

Temporary workaround is move "-> Result<(), Error>" to next line.

**Comment by imzeadom** [comment]
Thanks for fixing this issue.

**Comment by hdevalke** [comment]
Thank you for learning me about tests returning a result. I did not know it was allowed.
