### ISSUE TITLE
--nocapture

### ISSUE THREAD

**Issue by gilescope** [hdevalke/rust-test-lens#12]
Given that this is to debug individual tests, can we append --nocapture by default?
In many tdd cases you want to see the output of the test.

**Comment by hdevalke** [comment]
Good idea. Maybe I make this a configurable.
One configuration for tests, and one for the main function.

**Comment by gilescope** [comment]
Great. By default I would —nocapture unless multiple tests were being run.

**Comment by hdevalke** [comment]
I have a [branch](https://github.com/hdevalke/rust-test-lens/tree/issue-12) with the changes you requested. 
Would you mind to try it out?

If you open the repo in vscode you can go to _debug -> start debugging_ to try it out.

**Comment by hdevalke** [comment]
I published [v0.3.0](https://github.com/hdevalke/rust-test-lens/tree/v0.3.0) as it also solved another issue where `main` was always passed on as an argument when testing a binary.

Thanks for the suggestion
