### ISSUE TITLE
Add support for #[tokio::test]

### ISSUE THREAD

**Issue by gakonst** [hdevalke/rust-test-lens#13]
As title, you can run tests as `async fn` by adding `#[tokio::test]` above them, instead of `#[test]`. This feature is enabled by importing tokio `0.2.8` with the `macros` feature. 

It'd be nice if the addon could detect that tag and show the Run Test overlay

**Comment by hdevalke** [comment]
This should not be too much work as it is only adding an optional `tokio::` to the the regex [here](https://github.com/hdevalke/rust-test-lens/blob/master/src/RustCodeLensProvider.ts#L61).

[#[async_std::test]](https://docs.rs/async-std/1.4.0/async_std/attr.test.html) also exists. 

So I will add both. 

Do you have an example project I could use to test the functionality?

**Comment by hdevalke** [comment]
Apparently there is also the option to choose the scheduler:

```rs
#[tokio::test(threaded_scheduler)]
```

**Comment by hdevalke** [comment]
It should be available in the [marketplace](https://marketplace.visualstudio.com/items?itemName=hdevalke.rust-test-lens). Please reopen this ticket if you have any issue with it.
