### ISSUE TITLE
Do not open Debug tab at the left if no breakpoints or exceptions are hit

### ISSUE THREAD

**Issue by buybackoff** [hdevalke/rust-test-lens#14]
Thanks for this small but very useful extension!

Is it possible not to open the Debug tab at the left if no breakpoints or exceptions are hit? It's empty/useless and distracts from Explorer.

![image](https://user-images.githubusercontent.com/489852/72845322-a50fd900-3c9e-11ea-940f-6be2f2ebe04b.png)

This is actually a usability workaround for #1. I cannot find a way to run tests from nested workspaces, but debugging works. So debugging without breakpoints or exceptoins is kind of running :smirk:

**Comment by hdevalke** [comment]
I am afraid this is the default behavior in vscode to go to the debug tab when starting a debug session. Nothing in this extension is opening this tab. You can run CTRL+SHIFT+E to go back to the explorer tab.

I think it is better to file a bug in the rust extension you use.

Do you use the [RLS](https://github.com/rust-lang/rls-vscode) extension or [rust-analyzer](https://github.com/rust-analyzer/rust-analyzer/releases)?

**Comment by buybackoff** [comment]
I was using RSL. Have you seen https://github.com/swellaby/vscode-rust-test-adapter/issues/16 extension? It runs tests just fine with the same setup, but cannot debug yet. Maybe you could use code from there (it's MIT), obviously RLS or some workaround in that extension could run tests.

**Comment by hdevalke** [comment]
The `Run test` above the method is added by RLS, not by Rust test explorer plugin. If I would add a `Run test` above the test method, it be confusing for people that have RLS or Rust Analyzer installed.

Both RLS and Rust test explorer fail to work correctly with vscode workspaces, the latter works well with cargo workspaces. Rust Analyzer works well in both cases.

I can explain how it works. It might help swellaby/vscode-rust-test-adapter#16 to implement the debug feature.

This extension tries to find each test and creates a `DebugConfiguration` ([RustCodeLensProvider.ts#L117](
https://github.com/hdevalke/rust-test-lens/blob/master/src/RustCodeLensProvider.ts#L117)) compatible with the expectations of [vadimcn/vscode-lldb](https://github.com/vadimcn/vscode-lldb). 
When clicking on the lens, it will run a command ([RustCodeLensProvider.ts#L87](https://github.com/hdevalke/rust-test-lens/blob/master/src/RustCodeLensProvider.ts#L87)).
The command is created [here](https://github.com/hdevalke/rust-test-lens/blob/master/src/extension.ts#L74).

As it is not possible to change the default behavior of vs code when starting a debug session and there is a quick work around, rust analyzer, or adding a custom keyboard short cut for `View: show test`, I will close this issue.

**Comment by buybackoff** [comment]
BTW, thanks a lot for pointing me to rust-analyzer, I somehow missed it because it's not yet in VSCode marketplace.
