### ISSUE TITLE
Using  "#[should_panic]" breaks the "Run Test" button

### ISSUE THREAD

**Issue by sam-wright** [hdevalke/rust-test-lens#4]
The only button that shows up on tests that use     #[should_panic] is "Debug Test", the normal "Run Test" stopped showing up.

**Comment by hdevalke** [comment]
This extension only adds the "Debug Test". The "Run Test" is part of the rust vscode extension.

**Comment by sam-wright** [comment]
ah yes, thank you and the discussion there on [432](https://github.com/rust-lang/rls-vscode/issues/432) has a simple workaround (just reverse the order for now)
