### ISSUE TITLE
Support for workspace with Rust project in sub folder

### ISSUE THREAD

**Issue by liona24** [hdevalke/rust-test-lens#7]
Hey,

my current project setup has its rust component in a subfolder of the actual workspace, i.e.:
```
/
- .vscode/
--- ...
- rust-project/
--- Cargo.toml
--- src
```

This feature is supported in *beta* for the RLS extension.  
However I cannot find a way to configure this extension for custom cargo paths?

Is there a way to easily do this?

Also the `Debug Test` button seems to be completely missing. Clicking `Run Test` causes the test runner to fail with `could not find "Cargo.toml" in "/workspaces/my-workspace/" or any parent directory`

**Comment by hdevalke** [comment]
Hi, 

Thank you for reporting this issue. 
If I am able to reproduce this, I can have an idea if it is easy to do it.

Do you have only 1 `rust-project` or do you have multiple of them?

This plugin depends on [vscode-lldb](https://github.com/vadimcn/vscode-lldb), so even if I could solve the `could not find "Cargo.toml"` issue, it might still not work.

**Comment by hdevalke** [comment]
I tried out some stuff and it looks promising.
If you add the rust project as a workspace folder in your visual studio code project, you will be able to debug it. Any workspace folder containing a `Cargo.toml` file will have the debug lens. 

Just to be sure, is that what you mean by _subfolder of the actual workspace_?
![image](https://user-images.githubusercontent.com/2261239/68979696-843e8980-07fe-11ea-9850-ae2b3408f104.png)
 
I still have to test more thoroughly before this can be released.

**Comment by liona24** [comment]
Hey,

I have only one rust-project. Not sure if even the RLS could handle multiple projects.

I actually did not explicitly add the folder to the workspace (like you suggested). The project simple resides in a child directory of the workspace root, i.e. I have opened one folder as the workspace, and within that folder another folder contains my project. 

Hope I could clarify.

**Comment by hdevalke** [comment]
I put it on market place. Could you please confirm it is working as expected?

**Comment by liona24** [comment]
Hey,
thanks, it is working if I `Add folder to workspace`. 

This is fine, but I actually have to add my folder "twice" now, since it is technically already in the other folder, just not as a another workspace root.

**Comment by hdevalke** [comment]
I think there was some confusion between workspaces as defined by vscode and workspaces as defined by cargo. 

I installed the RLS extension (I use [rust-analyzer](https://github.com/rust-analyzer/rust-analyzer)).
After enabling `rust-client.enableMultiProjectSetup` It does find the test, but clicking on `Run test` fails with:

    > Executing task: cargo test -- --nocapture it_works <
    
    error: could not find `Cargo.toml` in `/home/hannes/tmp/bug-7` or any parent directory
    The terminal process terminated with exit code: 101

I think you are better of declaring a virtual manifest in the root of your project:

```
# ./Cargo.toml 
[workspace]
members = ["rust-project"]
```

That way both, the rls extension and the this extension work fine.

**Comment by liona24** [comment]
Well thanks I did not know about this feature until now. 

Though it does not seem to work out very well. Now I get two `Run test` buttons and the debug button is still missing:
![image](https://user-images.githubusercontent.com/25030208/69008220-69782c00-0948-11ea-8e18-69cc825cf486.png)

Running the tests (clicking on `Run test` and `Debug test`) without the `Cargo.toml` in the project root but adding the folders explicitly to the workspace seems to work just fine for me though.

**Comment by hdevalke** [comment]
The double `Run test` is probably a bug in vscode-rls, when using a root `Cargo.toml` and `rust-client.enableMultiProjectSetup`, but is not related to this extension, which only provide the `Debug test`.

It is possible you have to reopen vscode in order to make this extension work, as it does not track changes to `Cargo.toml`.

**Comment by liona24** [comment]
It is probably a bug, indeed. I now disabled `enableMultiProjectSetup` and reloaded VSCode. Everything seems to be working fine now. 

Thank You very much!
